name: webgpu

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.4

ffigen:
  output: 'lib/ffi/ffi_webgpu.dart'
  headers:
    entry-points:
      - 'libwebgpu/src/lib_webgpu.h'
