name: webgpu
version: 0.0.1
description: >-
  Dart bindings of the WebGPU graphics API.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.4
  lints: ^2.0.1
  test: ^1.16.0

# This should be run from libwebgpu/build.py, as it sets up the build folder prior to running ffigen.
ffigen:
  name: 'libwebgpu'
  description: >-
    Dart bindings of the WebGPU graphics API.
  output: 'lib/ffi/ffi_webgpu.dart'
  headers:
    entry-points:
      - 'libwebgpu/lib/lib_webgpu_dart.h'
